yprogram:
	g++ main.cpp handleMenu.cpp constant.cpp handleNewPage.cpp level1_loading_page.cpp level2_loading_page.cpp handlePlayWindow.cpp setting.cpp level2.cpp SurfaceToTexture.cpp mix_music.cpp name_input.cpp -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf && ./a.out
