yprogram:
	g++ main.cpp score.cpp exit.cpp handleMenu.cpp constant.cpp handleNewPage.cpp level1_loading_page.cpp level2_loading_page.cpp level3_loading_page.cpp level4_loading_page.cpp level5_loading_page.cpp handlePlayWindow.cpp setting.cpp level2.cpp level3.cpp level4.cpp level5.cpp SurfaceToTexture.cpp mix_music.cpp name_input.cpp -lSDL2 -lSDL2_image -lSDL2_mixer -lSDL2_ttf && ./a.out
